
services:

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  db:
    container_name: db
    image: postgres:17
    shm_size: 128mb
    healthcheck:
      test: [ "CMD", 'pg_isready', '-q', '-d', 'postgres', '-U', '${POSTGRES_USER}']
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASS: ${APP_DB_PASS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
      TZ: America/Chicago
    volumes:
      - ./psql/db:/var/lib/postgresql/data/pgdata
      - ./psql/init.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./psql/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "${POSTGRES_PORT}:5432"

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      TZ: America/Chicago
    volumes:
      - ./adminer/adminer-dark.css:/var/www/html/adminer.css

networks:
  default:
    external: true
    name: nprp_net