#!/usr/bin/env bash

set -e

export PGPASSWORD=${POSTGRES_PASSWORD}

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL

  CREATE USER ${APP_DB_USER} WITH PASSWORD '${APP_DB_PASS}';

  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${APP_DB_USER};
  GRANT pg_read_all_data TO ${APP_DB_USER};
  GRANT pg_write_all_data TO ${APP_DB_USER};

  \c ${POSTGRES_DB}

  GRANT USAGE ON SCHEMA public TO ${APP_DB_USER};
  GRANT ALL ON SCHEMA public TO ${APP_DB_USER};

  CREATE SCHEMA IF NOT EXISTS app;
  GRANT USAGE ON SCHEMA app TO ${APP_DB_USER};
  GRANT ALL ON SCHEMA app TO ${APP_DB_USER};

  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${APP_DB_USER};
  GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${APP_DB_USER};

EOSQL